databases:
  - name: greencode-db
    databaseName: greencode
    user: greencode
    region: frankfurt
    plan: free

services:
  - type: web
    name: greencode
    runtime: docker
    rootDir: server
    dockerfilePath: ./Dockerfile
    region: frankfurt
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://greencode-qg35.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        value: postgresql://greencode:SbGcj5aJA8UhbKOUSOW3goXQWKW3RUvl@dpg-d8qlihugvqtc73duempg-a/greencode_yohu
      - key: SANCTUM_STATEFUL_DOMAINS
        value: greencode-qg35.onrender.com
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_DOMAIN
        value: greencode-qg35.onrender.com
